name: CD

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "pushing image to dockerhub..."

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}


      - name: Switch to Current Branch
        run: git checkout main

      - name: Set Env
        run: echo "API_IMAGE=${{ secrets.DOCKER_USERNAME }}/spira-api:${{github.ref_name}}" >> $GITHUB_ENV
        run: echo "API_TEST_IMAGE=${{ secrets.DOCKER_USERNAME }}/spira-api-test:${{github.ref_name}}" >> $GITHUB_ENV


      - name: Push Image
        run: bash push-image.sh
      
