name: CD

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "pushing image to dockerhub..."

      - name: Set Env

        run: echo "RELEASE_VERSION=${GITHUB_REF#REFS/*/}" >> $GITHUB_ENV && echo "API_IMAGE=daitamae/spira-api:${RELEASE_VERSION}"

      - name: Push Image
        run: bash push_image.sh
      
